python train.py -mode train -task abs \
-bert_data_path /home/ybai/downloads/bert_data_cnndm_final/cnndm \
-model_path ../models_abs_baseline \
-log_file ../logs/cnndm_baseline \
-accum_count 5  \
-sep_optim false -lr 0.05 -dec_dropout 0.1 \
-batch_size 300 -train_steps 200000 -warmup_steps 8000 -report_every 50 \
-save_checkpoint_steps 2000 -seed 777 \
-use_bert_emb true -use_interval true \
-max_pos 512 -enc_hidden_size 512  -enc_layers 6 -enc_ff_size 2048 -enc_dropout 0.1 \
-dec_layers 6 -dec_hidden_size 512 -dec_ff_size 2048 \
-encoder baseline \
-visible_gpus 4